# Generated by Django 4.1.2 on 2023-02-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profession_profil_firstname_profil_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
    ]
