# Generated by Django 4.1.2 on 2023-02-15 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profil_confirm_password_profil_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='bithrDay',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
