# Generated by Django 4.1.2 on 2023-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
