# Generated by Django 4.1.2 on 2023-03-08 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_profil_user_alter_profil_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='username',
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
