# Generated by Django 3.2.19 on 2023-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profil_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
            ],
        ),
    ]
