# Generated by Django 3.2.19 on 2023-08-22 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
