# Generated by Django 3.2.19 on 2023-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='2023-08-22 00:00:00', max_length=128),
            preserve_default=False,
        ),
    ]
