# Generated by Django 3.2.19 on 2023-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_temporaryaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('code_postal', models.CharField(max_length=10)),
                ('adresse', models.TextField()),
                ('activation_code', models.CharField(max_length=6)),
            ],
        ),
    ]
