# Generated by Django 3.2.19 on 2023-08-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_temporaryaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccount',
            name='sexe',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10),
        ),
    ]
