# Generated by Django 3.2.19 on 2023-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='reserved_events', to='accounts.Account'),
        ),
    ]
