# Generated by Django 4.1.2 on 2023-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_reserveevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_artist",
                    models.CharField(max_length=255, verbose_name="Nom de l'artiste"),
                ),
                (
                    "price_artist",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix de l'événement",
                    ),
                ),
                (
                    "nbre_place_artist",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        verbose_name="Nombre de places disponibles",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        verbose_name="Date et heure de début de l'événement"
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        verbose_name="Date et heure de fin de l'événement"
                    ),
                ),
                (
                    "designation_artist",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Description de l'artiste",
                    ),
                ),
                (
                    "photo_artist",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Photo de l'artiste"
                    ),
                ),
                (
                    "is_featured_artist",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="En vedette"
                    ),
                ),
                (
                    "last_model_artist",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Dernier modèle",
                    ),
                ),
                (
                    "created_date_artist",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True, related_name="reserve", to="accounts.account"
                    ),
                ),
            ],
        ),
    ]
