# Generated by Django 4.1.2 on 2023-09-19 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_evenement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserveevent",
            name="account",
        ),
        migrations.RemoveField(
            model_name="reserveevent",
            name="event",
        ),
        migrations.DeleteModel(
            name="Events",
        ),
        migrations.DeleteModel(
            name="ReserveEvent",
        ),
    ]
