# Generated by Django 4.1.2 on 2023-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_remove_reserveevent_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="url_youtube",
            field=models.CharField(default="2023-09-19 17:00:00", max_length=255),
            preserve_default=False,
        ),
    ]
