# Generated by Django 4.1.2 on 2023-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_evenement_url_youtube"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="url_youtube",
            field=models.CharField(max_length=255, verbose_name="URL Youtube"),
        ),
    ]
