# Generated by Django 4.1.2 on 2023-09-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_remove_evenement_attendees_account_events_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="events_user",
        ),
        migrations.AddField(
            model_name="evenement",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="reserve", to="accounts.account"
            ),
        ),
    ]
