# Generated by Django 4.1.2 on 2023-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_remove_account_events_user_evenement_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="events_user",
            field=models.ManyToManyField(
                blank=True, related_name="registered_users", to="accounts.evenement"
            ),
        ),
    ]
