# Generated by Django 4.1.2 on 2023-01-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decription', models.TextField(blank=True, max_length=1000)),
                ('quantites', models.IntegerField(blank=True, default=0)),
                ('categorie', models.CharField(blank=True, max_length=45)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('adresse', models.CharField(blank=True, max_length=45)),
                ('telephone', models.CharField(blank=True, max_length=45)),
                ('prod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='base.product')),
            ],
        ),
    ]
