# Generated by Django 4.1.2 on 2023-04-05 07:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date_art', models.DateField(default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title_resp', models.CharField(blank=True, max_length=45)),
                ('message_resp', models.TextField(blank=True, max_length=1000)),
                ('created_date_resp', models.DateField(auto_now_add=True)),
                ('update_date_resp', models.DateField(default=datetime.date.today, null=True)),
                ('article_resp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.article')),
                ('user_resp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
